import classNames from 'classnames'
import './centerNetStatus.css'
import Tooltip from '../Utils/Tooltip'
import { toDecimal } from '../../util/numbers'

export default function CenterNetStatus({ Apy, secondary = false }) {
  const negative = Apy < 0
  const positive = Apy > 0

  return (
    <div className="center-net-status">
      <Tooltip
        slotProps={{
          popper: {
            modifiers: [
              {
                name: 'offset',
                options: {
                  offset: [0, 8],
                },
              },
            ],
          },
        }}
        title="This metric calculates the NET APR (Net Annual Return) by considering the positive interests generated by Supplied Assets and negative interests generated by Borrowed Assets."
      >
        <div
          className={classNames('center-circle', {
            negative,
            positive,
            secondary,
          })}
        >
          <p>Net APY</p>
          <p
            className="net-value"
            style={{ marginTop: '20px', fontSize: '30px' }}
          >
            {Apy != null ? toDecimal(Apy, 3) : 0} %
          </p>
        </div>
      </Tooltip>
    </div>
  )
}
